### ISSUE TITLE
Request to change the IRC link/button in opencv.org's footer

### ISSUE THREAD

**Issue by alalek** [opencv-infrastructure/opencv.org#46]
Details: https://github.com/opencv/opencv/issues/10245#issuecomment-861084011

**Comment by vikasgupta-github** [comment]
This has been changed.

**Comment by crackwitz** [comment]
Hello again. Confused people just pointed my attention to https://github.com/opencv/opencv/wiki/GSoC_2024#resources which mentions freenode.

One other instance in the wikis: https://github.com/opencv/opencv/wiki/OpenCV_GSoC_Application

Could these two be edited as well?

The [2023](https://github.com/opencv/opencv/wiki/GSoC_2023#resources) and [2022](https://github.com/opencv/opencv/wiki/GSoC_2022#resources) pages still mention freenode as well. Since all that ugly business happened in 2021, I think it's fair to keep anything from 2021 and earlier as is. I don't know what to suggest about material after 2021 that is already "historical", like those GSoCs are.

**Comment by mshabunin** [comment]
Thank you. I've updated GSoC 2024 and GSoC template pages, left other pages intact.
